using Microsoft.AspNetCore.Mvc.Rendering;

namespace Librelia.Database
{
    public static class StaticValues
    {
        public static int bookForUser = 2;
        public static int itemsForPage = 50;
        public static Dictionary<string, string> categoryBooks = new Dictionary<string, string>
        {
            { "Narrativa", "fiction" },
            { "Saggistica", "non-fiction" },
            { "Fantascienza", "fantascienza" },
            { "Fantasy", "fantasy" },
            { "Horror", "horror" },
            { "Giallo", "giallo" },
            { "Romantico", "romantico" },
            { "Thriller", "thriller" },
            { "Narrativa Storica", "narrativa-storica" },
            { "Biografia", "biografia" },
            { "Autoaiuto", "autoaiuto" },
            { "Salute", "salute" },
            { "Cucina", "cucina" },
            { "Arte", "arte" },
            { "Poesia", "poesia" },
            { "Filosofia", "filosofia" },
            { "Psicologia", "psicologia" },
            { "Letteratura per bambini", "letteratura-per-bambini" },
            { "Young Adult", "young-adult" },
            { "Classici", "classici" },
            { "Avventura", "avventura" },
            { "Scienza", "scienza" },
            { "Religione", "religione" },
            { "Economia", "economia" },
            { "Educazione", "educazione" },
            { "Viaggi", "viaggi" },
            { "Sport", "sport" },
            { "Musica", "musica" },
            { "Politica", "politica" },
            { "Tecnologia", "tecnologia" },
            { "Genitorialità", "genitorialità" },
            { "Crimine vero", "crimine-vero" },
            { "Spiritualità", "spiritualità" },
            { "Umorismo", "umorismo" },
            { "Fumetti", "fumetti" },
            { "Fotografia", "fotografia" },
            { "Lavori manuali e hobby", "lavori-manuali-e-hobby" },
            { "Informatica", "informatica" },
            { "Ambiente", "ambiente" },
            { "Antropologia", "antropologia" },
            { "Scienze sociali", "scienze-sociali" },
            { "Corpo, mente e spirito", "corpo-mente-e-spirito" },
            { "Senza categoria", "uncategorized" },
            { "Religione e spiritualità", "religione" },
            { "Arti", "arte" },
            { "Raccolte letterarie", "collezioni-letterarie" },
            { "Teatro", "teatro" },
            { "Storia", "storia" },
            { "Letteratura per ragazzi", "letteratura-per-ragazzi" },
            { "Economia e business", "economia-e-business" },
            { "Legge", "legge" },
            { "Medicina", "medicina" },
            { "Scienze politiche", "scienze-politiche" },
            { "Famiglia e relazioni", "famiglia-e-relazioni" },
            { "Linguistica", "linguistica" },
            { "Arti performative", "arti-performative" },
            { "Riferimento", "reference" },
            { "Sussidi didattici", "sussidi-didattici" },
            { "Trasporti", "trasporti" },
            { "Architettura", "architettura" },
            { "Giardinaggio", "giardinaggio" },
            { "Animali domestici", "animali-domestici" },
            { "Giochi e attività", "giochi-e-attività" },
            { "Casa e giardino", "casa-e-giardino" },
            { "Natura", "natura" },
            { "Matematica", "matematica" },
            { "Bibbia", "bibbie" },
            { "Studio delle lingue straniere", "studio-lingue-straniere" },
            { "Critica letteraria", "critica-letteraria" }
        };


        public static List<SelectListItem> categoryList = new List<SelectListItem>()
        {
            new SelectListItem { Text = "Narrativa", Value = "fiction" },
            new SelectListItem { Text = "Saggistica", Value = "non-fiction" },
            new SelectListItem { Text = "Fantascienza", Value = "fantascienza" },
            new SelectListItem { Text = "Fantasy", Value = "fantasy" },
            new SelectListItem { Text = "Horror", Value = "horror" },
            new SelectListItem { Text = "Giallo", Value = "giallo" },
            new SelectListItem { Text = "Romantico", Value = "romantico" },
            new SelectListItem { Text = "Thriller", Value = "thriller" },
            new SelectListItem { Text = "Narrativa Storica", Value = "narrativa-storica" },
            new SelectListItem { Text = "Biografia", Value = "biografia" },
            new SelectListItem { Text = "Autoaiuto", Value = "autoaiuto" },
            new SelectListItem { Text = "Salute", Value = "salute" },
            new SelectListItem { Text = "Cucina", Value = "cucina" },
            new SelectListItem { Text = "Arte", Value = "arte" },
            new SelectListItem { Text = "Poesia", Value = "poesia" },
            new SelectListItem { Text = "Filosofia", Value = "filosofia" },
            new SelectListItem { Text = "Psicologia", Value = "psicologia" },
            new SelectListItem { Text = "Letteratura per bambini", Value = "letteratura-per-bambini" },
            new SelectListItem { Text = "Young Adult", Value = "young-adult" },
            new SelectListItem { Text = "Classici", Value = "classici" },
            new SelectListItem { Text = "Avventura", Value = "avventura" },
            new SelectListItem { Text = "Scienza", Value = "scienza" },
            new SelectListItem { Text = "Religione", Value = "religione" },
            new SelectListItem { Text = "Economia", Value = "economia" },
            new SelectListItem { Text = "Educazione", Value = "educazione" },
            new SelectListItem { Text = "Viaggi", Value = "viaggi" },
            new SelectListItem { Text = "Sport", Value = "sport" },
            new SelectListItem { Text = "Musica", Value = "musica" },
            new SelectListItem { Text = "Politica", Value = "politica" },
            new SelectListItem { Text = "Tecnologia", Value = "tecnologia" },
            new SelectListItem { Text = "Genitorialità", Value = "genitorialità" },
            new SelectListItem { Text = "Crimine vero", Value = "crimine-vero" },
            new SelectListItem { Text = "Spiritualità", Value = "spiritualità" },
            new SelectListItem { Text = "Umorismo", Value = "umorismo" },
            new SelectListItem { Text = "Fumetti", Value = "fumetti" },
            new SelectListItem { Text = "Fotografia", Value = "fotografia" },
            new SelectListItem { Text = "Lavori manuali e hobby", Value = "lavori-manuali-e-hobby" },
            new SelectListItem { Text = "Informatica", Value = "informatica" },
            new SelectListItem { Text = "Ambiente", Value = "ambiente" },
            new SelectListItem { Text = "Antropologia", Value = "antropologia" },
            new SelectListItem { Text = "Scienze sociali", Value = "scienze-sociali" },
            new SelectListItem { Text = "Corpo, mente e spirito", Value = "corpo-mente-e-spirito" },
            new SelectListItem { Text = "Senza categoria", Value = "uncategorized" },
            new SelectListItem { Text = "Religione e spiritualità", Value = "religione" },
            new SelectListItem { Text = "Arti", Value = "arte" },
            new SelectListItem { Text = "Raccolte letterarie", Value = "collezioni-letterarie" },
            new SelectListItem { Text = "Teatro", Value = "teatro" },
            new SelectListItem { Text = "Storia", Value = "storia" },
            new SelectListItem { Text = "Letteratura per ragazzi", Value = "letteratura-per-ragazzi" },
            new SelectListItem { Text = "Economia e business", Value = "economia-e-business" },
            new SelectListItem { Text = "Legge", Value = "legge" },
            new SelectListItem { Text = "Medicina", Value = "medicina" },
            new SelectListItem { Text = "Scienze politiche", Value = "scienze-politiche" },
            new SelectListItem { Text = "Famiglia e relazioni", Value = "famiglia-e-relazioni" },
            new SelectListItem { Text = "Linguistica", Value = "linguistica" },
            new SelectListItem { Text = "Arti performative", Value = "arti-performative" },
            new SelectListItem { Text = "Riferimento", Value = "reference" },
            new SelectListItem { Text = "Sussidi didattici", Value = "sussidi-didattici" },
            new SelectListItem { Text = "Trasporti", Value = "trasporti" },
            new SelectListItem { Text = "Architettura", Value = "architettura" },
            new SelectListItem { Text = "Giardinaggio", Value = "giardinaggio" },
            new SelectListItem { Text = "Animali domestici", Value = "animali-domestici" },
            new SelectListItem { Text = "Giochi e attività", Value = "giochi-e-attività" },
            new SelectListItem { Text = "Casa e giardino", Value = "casa-e-giardino" },
            new SelectListItem { Text = "Natura", Value = "natura" },
            new SelectListItem { Text = "Matematica", Value = "matematica" },
            new SelectListItem { Text = "Bibbia", Value = "bibbie" },
            new SelectListItem { Text = "Studio delle lingue straniere", Value = "studio-lingue-straniere" },
            new SelectListItem { Text = "Critica letteraria", Value = "critica-letteraria" }
        };

    }
}
